[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts', '@openzeppelin@v4.8.3/contracts=lib/openzeppelin-contracts@v4.8.3/contracts', '@openzeppelin-upgradeable@v4.8.3/contracts=lib/openzeppelin-contracts-upgradeable@v4.8.3/contracts']
ffi = true 
# only if you are confident on what you are running
fs_permissions = [{ access = "read", path = "./broadcast" }]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
